name: Go
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      # - name: Install Atlas
      #   run: go install -tags sqlite github.com/gobuffalo/pop/v6/soda@latest
      # - name: Test
      #   run: make test
      - name: Build
        run: make build
